### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by soyuka** [Tjatse/pm2-ant#1]
This is a nice idea! Let me know if you need help or want to discuss things, this seems very interessant.

A few days ago I made some benchmarkings to proof that the memory leak wasn't coming from pm2. You can find everything on https://github.com/soyuka/nodejs-http-memtest. I didn't use statsd, I just monitored a pid every seconds and wrote data in a csv. This csv is then transformed to a graph using gnu-plot. Might give you ideas, or not :).

Gl.

**Comment by Tjatse** [comment]
Ha, thats very nice of you buddy, I'll check out that, thanks anyway.
Since PM2@0.14.0, it seems very easy to crash. So we need a distributed time series database (Influxdb / Graphite) to analyze PM2 notable events (Stay alert, track problem, monitor the health of server). All I need to do is to demerge it from our products now :)

Powered by Graphana:
![20150806](https://cloud.githubusercontent.com/assets/1418444/9109657/df08ee1a-3c69-11e5-92ae-719a98739244.jpg)

**Comment by soyuka** [comment]
The 0.14 issue was related to the gc feature, it was removed in 0.14.5. Did
you had segfaults on centos?
Graphana looks really nice, are you working for them? Or does this pm2
monitoring feature belong to one of your products?

**Comment by Tjatse** [comment]
Yap, thats the point.
I'm not working for Graphana / Kibana, just a normal user.
Yes, this monitor feature belongs to one of my product, and there're too many other interesting stuffs related to PM2, you known, I am a huge fan of PM2 :)

**Comment by soyuka** [comment]
\o/ who is not!
